CREATE TABLE combined_data_df (
	MONTH INT,
	DAY INT,
	YEAR INT,
	WEEKDAY VARCHAR(255),
	DESTINATION_AIRPORT VARCHAR(255),
	AIRPORT VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	ORIGIN_AIRPORT VARCHAR(255),
	AIRLINE VARCHAR(255),
	FLIGHT_NUMBER INT,
	SCHEDULED_DEPARTURE INT,
	SCHEDULED_ARRIVAL INT,
	DISTANCE INT
);